/*

 BKG.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
UINT16 bkgCGB[] =
{
  RGB_WHITE, RGB_CYAN, RGB_GREEN, RGB_GREEN
};
/* Start of tile array. */
unsigned char bkg[] =
{
  0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
  0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
  0xF3,0x00,0xE1,0x00,0xF3,0x00,0xFF,0x00,
  0x9F,0x60,0x0C,0xF3,0x00,0xFF,0x00,0xFF
};

/* End of BKG.C */
