/*

 BKGEX.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 12
   Tile set      : C:\Users\abzar\Documents\workspace\GameBoy\GameBoyGames\gbSource\RPG\bkgTiles\gbrFiles\bkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 45
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkgExWidth 20
#define bkgExHeight 12
#define bkgExBank 0

extern unsigned char bkgEx[];

/* End of BKGEX.H */
