/*

 JERD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define jerdBank 0

/* Super Gameboy palette 0 */
#define jerdSGBPal0c0 6076
#define jerdSGBPal0c1 8935
#define jerdSGBPal0c2 6596
#define jerdSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define jerdSGBPal1c0 6076
#define jerdSGBPal1c1 8935
#define jerdSGBPal1c2 6596
#define jerdSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define jerdSGBPal2c0 6076
#define jerdSGBPal2c1 8935
#define jerdSGBPal2c2 6596
#define jerdSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define jerdSGBPal3c0 6076
#define jerdSGBPal3c1 8935
#define jerdSGBPal3c2 6596
#define jerdSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define jerdCGBPal0c0 6076
#define jerdCGBPal0c1 27550
#define jerdCGBPal0c2 26624
#define jerdCGBPal0c3 0

/* Gameboy Color palette 1 */
#define jerdCGBPal1c0 6076
#define jerdCGBPal1c1 21342
#define jerdCGBPal1c2 217
#define jerdCGBPal1c3 0

/* Gameboy Color palette 2 */
#define jerdCGBPal2c0 6076
#define jerdCGBPal2c1 8935
#define jerdCGBPal2c2 6596
#define jerdCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define jerdCGBPal3c0 6076
#define jerdCGBPal3c1 8935
#define jerdCGBPal3c2 6596
#define jerdCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define jerdCGBPal4c0 6076
#define jerdCGBPal4c1 8935
#define jerdCGBPal4c2 6596
#define jerdCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define jerdCGBPal5c0 6076
#define jerdCGBPal5c1 8935
#define jerdCGBPal5c2 6596
#define jerdCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define jerdCGBPal6c0 6076
#define jerdCGBPal6c1 8935
#define jerdCGBPal6c2 6596
#define jerdCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define jerdCGBPal7c0 6076
#define jerdCGBPal7c1 8935
#define jerdCGBPal7c2 6596
#define jerdCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char jerdCGB[];
/* Start of tile array. */
extern unsigned char jerd[];

/* End of JERD.H */
