/*

 JIRARD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define jirardBank 0

/* Super Gameboy palette 0 */
#define jirardSGBPal0c0 6076
#define jirardSGBPal0c1 8935
#define jirardSGBPal0c2 6596
#define jirardSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define jirardSGBPal1c0 6076
#define jirardSGBPal1c1 8935
#define jirardSGBPal1c2 6596
#define jirardSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define jirardSGBPal2c0 6076
#define jirardSGBPal2c1 8935
#define jirardSGBPal2c2 6596
#define jirardSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define jirardSGBPal3c0 6076
#define jirardSGBPal3c1 8935
#define jirardSGBPal3c2 6596
#define jirardSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define jirardCGBPal0c0 6076
#define jirardCGBPal0c1 27550
#define jirardCGBPal0c2 26624
#define jirardCGBPal0c3 0

/* Gameboy Color palette 1 */
#define jirardCGBPal1c0 6076
#define jirardCGBPal1c1 21342
#define jirardCGBPal1c2 217
#define jirardCGBPal1c3 0

/* Gameboy Color palette 2 */
#define jirardCGBPal2c0 6076
#define jirardCGBPal2c1 8935
#define jirardCGBPal2c2 6596
#define jirardCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define jirardCGBPal3c0 6076
#define jirardCGBPal3c1 8935
#define jirardCGBPal3c2 6596
#define jirardCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define jirardCGBPal4c0 6076
#define jirardCGBPal4c1 8935
#define jirardCGBPal4c2 6596
#define jirardCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define jirardCGBPal5c0 6076
#define jirardCGBPal5c1 8935
#define jirardCGBPal5c2 6596
#define jirardCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define jirardCGBPal6c0 6076
#define jirardCGBPal6c1 8935
#define jirardCGBPal6c2 6596
#define jirardCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define jirardCGBPal7c0 6076
#define jirardCGBPal7c1 8935
#define jirardCGBPal7c2 6596
#define jirardCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char jirardCGB[];
/* Start of tile array. */
extern unsigned char jirard[];

/* End of JIRARD.H */
