/*

 HUDEXAMPLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : C:\Users\abzar\Documents\workspace\GameBoy\GameBoyGames\gbSource\bkgTiles\hud.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 20
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudExampleWidth 20
#define hudExampleHeight 2
#define hudExampleBank 0

extern unsigned char hudExample[];

/* End of HUDEXAMPLE.H */
