/*

 HUD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 44

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define hudBank 0

/* Super Gameboy palette 0 */
#define hudSGBPal0c0 6076
#define hudSGBPal0c1 8935
#define hudSGBPal0c2 6596
#define hudSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define hudSGBPal1c0 6076
#define hudSGBPal1c1 8935
#define hudSGBPal1c2 6596
#define hudSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define hudSGBPal2c0 6076
#define hudSGBPal2c1 8935
#define hudSGBPal2c2 6596
#define hudSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define hudSGBPal3c0 6076
#define hudSGBPal3c1 8935
#define hudSGBPal3c2 6596
#define hudSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define hudCGBPal0c0 32767
#define hudCGBPal0c1 24311
#define hudCGBPal0c2 23552
#define hudCGBPal0c3 0

/* Gameboy Color palette 1 */
#define hudCGBPal1c0 6076
#define hudCGBPal1c1 8935
#define hudCGBPal1c2 6596
#define hudCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define hudCGBPal2c0 6076
#define hudCGBPal2c1 8935
#define hudCGBPal2c2 6596
#define hudCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define hudCGBPal3c0 6076
#define hudCGBPal3c1 8935
#define hudCGBPal3c2 6596
#define hudCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define hudCGBPal4c0 6076
#define hudCGBPal4c1 8935
#define hudCGBPal4c2 6596
#define hudCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define hudCGBPal5c0 6076
#define hudCGBPal5c1 8935
#define hudCGBPal5c2 6596
#define hudCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define hudCGBPal6c0 6076
#define hudCGBPal6c1 8935
#define hudCGBPal6c2 6596
#define hudCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define hudCGBPal7c0 6076
#define hudCGBPal7c1 8935
#define hudCGBPal7c2 6596
#define hudCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char hudCGB[];
/* Start of tile array. */
extern unsigned char hud[];

/* End of HUD.H */
