/*

 HUDEX.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : C:\Users\abzar\Documents\workspace\GameBoy\GameBoyGames\gbSource\RPG\winTiles\gbrFiles\hud.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudExWidth 20
#define hudExHeight 6
#define hudExBank 0

extern unsigned char hudEx[];

/* End of HUDEX.H */
