/*

 LEVELONE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 10
   Tile set      : C:\Users\abzar\Documents\GBDTools\GameBoyGames\gbSource\bkgTiles\castle.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define levelOneWidth 10
#define levelOneHeight 10
#define levelOneBank 0

const unsigned char levelOne[] =
{
  0x44,0x44,0x44,0x44,0x44,0x40,0x00,0x00,0x00,
  0x00,0x40,0x00,0x00,0x00,0x00,0x40,0x20,0x10,
  0x20,0x10,0x40,0x00,0x00,0x00,0x00,0x40
};

/* End of LEVELONE.C */
