/*

 LEVELONE.H

 Map Include File.

 Info:
   Section       : i
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : C:\Users\abzar\Documents\workspace\GameBoy\GameBoyGames\gbSource\bkgTiles\castle.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define levelOneWidth 20
#define levelOneHeight 16
#define levelOneBank 0

extern unsigned char levelOne[];

/* End of LEVELONE.H */
